[package]
name = "rust_ffi_example"
version = "0.1.0"
edition = "2024"

# This is not needed by Bazel, instead it should be put in .rs file
# itself or in the BUILD.bazel rust_library entry (when supported...)
#[lib]
#crate-type = ["cdylib"]

[dependencies]